/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MCIMX6Z0xxx09
package_id: MCIMX6Z0DVM09
mcu_data: ksdk2_0
processor_version: 8.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: ca7}
- pin_list:
  - {pin_num: B3, peripheral: USDHC1, signal: 'usdhc_data, 0', pin_signal: SD1_DATA0}
  - {pin_num: B2, peripheral: USDHC1, signal: 'usdhc_data, 1', pin_signal: SD1_DATA1}
  - {pin_num: B1, peripheral: USDHC1, signal: 'usdhc_data, 2', pin_signal: SD1_DATA2}
  - {pin_num: A2, peripheral: USDHC1, signal: 'usdhc_data, 3', pin_signal: SD1_DATA3}
  - {pin_num: C2, peripheral: USDHC1, signal: usdhc_cmd, pin_signal: SD1_CMD}
  - {pin_num: C1, peripheral: USDHC1, signal: usdhc_clk, pin_signal: SD1_CLK}
  - {pin_num: J14, peripheral: USDHC1, signal: usdhc_cd_b, pin_signal: UART1_RTS_B}
  - {pin_num: D8, peripheral: USDHC2, signal: usdhc_clk, pin_signal: NAND_RE_B}
  - {pin_num: C8, peripheral: USDHC2, signal: usdhc_cmd, pin_signal: NAND_WE_B}
  - {pin_num: B7, peripheral: USDHC2, signal: 'usdhc_data, 1', pin_signal: NAND_DATA01}
  - {pin_num: D7, peripheral: USDHC2, signal: 'usdhc_data, 0', pin_signal: NAND_DATA00}
  - {pin_num: A7, peripheral: USDHC2, signal: 'usdhc_data, 2', pin_signal: NAND_DATA02}
  - {pin_num: D6, peripheral: USDHC2, signal: 'usdhc_data, 3', pin_signal: NAND_DATA03}
  - {pin_num: K14, peripheral: UART1, signal: uart_tx, pin_signal: UART1_TX_DATA}
  - {pin_num: K16, peripheral: UART1, signal: uart_rx, pin_signal: UART1_RX_DATA}
  - {pin_num: J17, peripheral: UART2, signal: uart_tx, pin_signal: UART2_TX_DATA}
  - {pin_num: J16, peripheral: UART2, signal: uart_rx, pin_signal: UART2_RX_DATA}
  - {pin_num: H14, peripheral: UART2, signal: uart_rts_b, pin_signal: UART2_RTS_B}
  - {pin_num: J15, peripheral: UART2, signal: uart_cts_b, pin_signal: UART2_CTS_B}
  - {pin_num: N17, peripheral: PWM1, signal: pwm_out, pin_signal: GPIO1_IO08}
  - {pin_num: M15, peripheral: PWM2, signal: pwm_out, pin_signal: GPIO1_IO09}
  - {pin_num: M16, peripheral: PWM3, signal: pwm_out, pin_signal: GPIO1_IO04}
  - {pin_num: M17, peripheral: PWM4, signal: pwm_out, pin_signal: GPIO1_IO05}
  - {pin_num: G17, peripheral: I2C1, signal: i2c_scl, pin_signal: UART4_TX_DATA}
  - {pin_num: G16, peripheral: I2C1, signal: i2c_sda, pin_signal: UART4_RX_DATA}
  - {pin_num: E1, peripheral: SAI1, signal: sai_rx_bclk, pin_signal: SD2_DATA03}
  - {pin_num: E3, peripheral: SAI1, signal: sai_mclk, pin_signal: SD2_DATA01}
  - {pin_num: D2, peripheral: SAI1, signal: sai_rx_data, pin_signal: SD2_DATA06}
  - {pin_num: E2, peripheral: SAI1, signal: sai_rx_sync, pin_signal: SD2_DATA02}
  - {pin_num: D3, peripheral: SAI1, signal: sai_tx_bclk, pin_signal: SD2_DATA05}
  - {pin_num: D1, peripheral: SAI1, signal: sai_tx_data, pin_signal: SD2_DATA07}
  - {pin_num: D4, peripheral: SAI1, signal: sai_tx_sync, pin_signal: SD2_DATA04}
  - {pin_num: K13, peripheral: USB, signal: usb_otg1_id, pin_signal: GPIO1_IO00}
  - {pin_num: D17, peripheral: USB, signal: usb_otg2_id, pin_signal: KPP_ROW7}
  - {pin_num: E6, peripheral: QSPI, signal: qspi_a_ss0_b, pin_signal: NAND_DQS}
  - {pin_num: A5, peripheral: QSPI, signal: qspi_a_ss1_b, pin_signal: NAND_DATA07}
  - {pin_num: D5, peripheral: QSPI, signal: qspi_a_sclk, pin_signal: NAND_WP_B}
  - {pin_num: A3, peripheral: QSPI, signal: 'qspi_a_data, 0', pin_signal: NAND_READY_B}
  - {pin_num: C5, peripheral: QSPI, signal: 'qspi_a_data, 1', pin_signal: NAND_CE0_B}
  - {pin_num: B5, peripheral: QSPI, signal: 'qspi_a_data, 2', pin_signal: NAND_CE1_B}
  - {pin_num: A4, peripheral: QSPI, signal: 'qspi_a_data, 3', pin_signal: NAND_CLE}
  - {pin_num: B4, peripheral: QSPI, signal: qspi_a_dqs, pin_signal: NAND_ALE}
  - {pin_num: H16, peripheral: UART3, signal: uart_rx, pin_signal: UART3_RX_DATA}
  - {pin_num: H17, peripheral: UART3, signal: uart_tx, pin_signal: UART3_TX_DATA}
  - {pin_num: G14, peripheral: UART3, signal: uart_rts_b, pin_signal: UART3_RTS_B}
  - {pin_num: H15, peripheral: UART3, signal: uart_cts_b, pin_signal: UART3_CTS_B}
  - {pin_num: M15, peripheral: SPDIF, signal: spdif_in, pin_signal: GPIO1_IO09}
  - {pin_num: N17, peripheral: SPDIF, signal: spdif_out, pin_signal: GPIO1_IO08}
  - {pin_num: F17, peripheral: I2C2, signal: i2c_scl, pin_signal: I2C2_SCL}
  - {pin_num: G13, peripheral: I2C2, signal: i2c_sda, pin_signal: I2C2_SDA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A7[ca7] */
  /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO00_USB_OTG1_ID , 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO04_PWM3_OUT , 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO05_PWM4_OUT , 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C2_SCL_I2C2_SCL , 0U);
    IOMUXC_SetPinMux(IOMUXC_I2C2_SDA_I2C2_SDA , 0U);
    IOMUXC_SetPinMux(IOMUXC_KPP_ROW7_USB_OTG2_ID , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_ALE_QSPI_A_DQS , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE0_B_QSPI_A_DATA01 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE1_B_QSPI_A_DATA02 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CLE_QSPI_A_DATA03 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA00_USDHC2_DATA0 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA01_USDHC2_DATA1 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA02_USDHC2_DATA2 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA03_USDHC2_DATA3 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA07_QSPI_A_SS1_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DQS_QSPI_A_SS0_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_READY_B_QSPI_A_DATA00 , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_RE_B_USDHC2_CLK , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_WE_B_USDHC2_CMD , 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_WP_B_QSPI_A_SCLK , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CLK_USDHC1_CLK , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CMD_USDHC1_CMD , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA0_USDHC1_DATA0 , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA1_USDHC1_DATA1 , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA2_USDHC1_DATA2 , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA3_USDHC1_DATA3 , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA01_SAI1_MCLK , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA02_SAI1_RX_SYNC , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA03_SAI1_RX_BCLK , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA04_SAI1_TX_SYNC , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA05_SAI1_TX_BCLK , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA06_SAI1_RX_DATA , 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA07_SAI1_TX_DATA , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_RTS_B_USDHC1_CD_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_RX_DATA_UART1_RX , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_TX_DATA_UART1_TX , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_CTS_B_UART2_CTS_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_RTS_B_UART2_RTS_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_RX_DATA_UART2_RX , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_TX_DATA_UART2_TX , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_CTS_B_UART3_CTS_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_RTS_B_UART3_RTS_B , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_RX_DATA_UART3_RX , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_TX_DATA_UART3_TX , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_RX_DATA_I2C1_SDA , 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_TX_DATA_I2C1_SCL , 0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
